### ISSUE TITLE
Yahoo's Social Directory Web Service API end of life

### ISSUE THREAD

**Issue by sunny** [karan-pathak/omniauth-yahoo_auth#3]
Hi!

The public Social Directory API is [ending its life on March 2nd, 2020](https://developer.yahoo.com/oauth/social-directory-eol/?guccounter=2). It needs to be replaced by the UserInfo Endpoint, which is OAuth 2.0 protected.

**Comment by mcohen9** [comment]
how do we fix this?

**Comment by sunny** [comment]
@mcohen9: No news from @karan-pathak so I guess that someone should fork this and update the API calls to use OAuth to fetch information about users.

@ikylin @ShalabhTripathi @NehaChopra @jindalmahima @rajatsingla @hackmdio: since you all have either watched or starred this repository, perhaps you have already adapted this on your services?

**Comment by louie728** [comment]
Does anyone have a newly updated strategy for https://api.login.yahoo.com/openid/v1/userinfo ?

**Comment by sunny** [comment]
@louie728 Forked and fixed in #4 🎉

**Comment by louie728** [comment]
Thanks @sunny appreciate that ...  Do I need to setup a new app with yahoo or should my existing creds work?

**Comment by sunny** [comment]
You can keep the same credentials and just point to the fork using `git:`.

**Comment by louie728** [comment]
@sunny thanks.  I actually didnt have openid prems on the app and yahoo doesn't allow the addition for some odd reason so I had to recreate.  Thanks again..

**Comment by killondark** [comment]
Hi @sunny. I use your fork but the response have a key `uid=nil` and it value need for me. Can you help for me? May be use for `uid` `sub` key, what do you think?

**Comment by sunny** [comment]
Hey @killondark, maybe `sub` could be a good key to use. How did you use `uid` with the gem before? Can you try using `sub` from the `extra` params?
